<?php 

	require '../visual/include/header.php';

 ?>
<?php 

	require '../visual/include/menu.php';

 ?>

<section class="main">

			<!-- Contenido de la pagina -->

			<h1>Club Canofilo Deportivo</h1>
			<article>
				<p>ADKANZ SERA EL MEDIADOR ENTRE EL PROPIETARIO Y EL PERRO, AYUDANDO A FORMAR UNA INTEGRACION
				FAMILIAR, ASI COMO ESTAR SIN PROBLEMAS EN PUBLICO Y OTROS LUGARES.</p>

				<p>POR MEDIO DE EDUCACION Y ADIESTRAMIENTO CANINO, PROVEEDOR ADKANZ, QUE CUENTA CON UN
				INSTRUCTOR CERTIFICADO POR LA U DE G. Y ANEPPAC (ASOCIACION NACIONAL DE ENTRENADORES PROFESIONALES DE PERROS A.C.).</p>

				<p>EL PROGRAMA CONSISTE EN UNA OBEDIENCIA BASICA, RAIZ DEL RESTO A DESARROLLARSE, QUE
				CONSISTE EN CAMINAR CON EL PERRO A DIFERENTES PASOS Y CAMBIOS DE VELOCIDAD, QUIETOS POR PARTE DEL PERRO A LA ORDEN EL PROPIETARIO YA SEA SENTADO O ECHADO, SERAN REALIZADOS CON COLLAR Y CORREA, MEDIDAS DE LOS ACCESORIOS SERAN DADAS POR EL INSTRUCTOR CANINO PRESENTE.</p>

				<p>CON UN HORARIO DE 2 HORAS A 3HORAS (A PARTIR DE LAS 8AM CON 15 MIN DE TOLERANCIA)). <br>
				SABADO O DOMINGO A ELEGIR. (UNA VEZ POR MES)</p>

				<p>LOS PERROS QUE HARAN SU FUNCION COMO PROTECTOR Y GUARDIAN, SERAN LLEVAMOS CON SERIEDAD, <br> 
				AQUEL QUE NO SE APEGUE A LOS PASOS DE SEGURIDAD, SE LE NEGARA DICHO SERVICIO.</p>

				<p>TODAS LA RAZAS SON ADMITIDAS, CUBRIENDO CADA UNA LA CUOTA POR LA CLASE, SE DARA ASESORIA CUBRIENDO LAS NECESIDADES DE CADA PERSONA EN CONJUNTO CON SU PERRO(S). </p>

				<p>CADA PROPIETARIO SE HARA CARGO DE SU PERRO SI ESTE HICIERA SUS NECESIDADES FISIOLOGICAS, ASI COMO SER RESPONSABLE DE LA SEGURIDAD DE LOS DEMAS RESPECTO A SU PERRO </p>

				<p>TODOS LOS PERROS DEBERAN ESTAR AL CORRIENTE DE SUS VACUNAS..</p>

				<h2>REQUISITOS</h2>

				
				<ol>
					<li>CUBRIR LA CUOTA ANTES DE COMENZAR LA CLASE</li>
					<li>CADA PERSONA DEL CLUB DEBERA TRAER SU EQUIPO NECESARIO DE ACUERDO A LAS NECESDADES Y LAS EDADES SIN IMPORTAR DE QUER RAZA SEAN</li>
					<li>COLLAR DE CORRECION Y CORREA</li>
					<li>PREMIO YA SEA GERGA, JUGUETE, COMIDA</li>
					<li>LOS QUE MUERDAN EN GUARDIA Y PROTECCION SU COLLAR DE AGITACION O INTERVENCION</li>
					<li>SILBATO</li>
					<li>EDAD MINIMA PARA ESTAR EN EL CLUB (CACHORROS), AL COMPLETAR SU CARTILLA DE VACUNACION Y DEPARACITACION) 4 MESE MAS O MENOS</li>
				</ol>
				
					<h2>REGLAMENTO</h2>
				<ol>
					<li>TENER EN TODO MOMENTO CONTROL SOBRE SU PERRO (AUNQUE SEA CACHORRO) PARA EVITAR ACCIDENTES Y LIMPIAR SUS ESES FECALES SI LLEGARAN HACER
					</li>
					<li>CADA VEZ QUE VAYA EL PERRO DEBERA SER EL MISMO MANEJADOR ( EN CASO DE SER OTRA PERSONA SE HARA AJUSTE DE LOS EJERCICIOS)
					</li>
					<li>ESTAR ATENTOS A LAS INDICACIONES DEL INSTRUCTOR</li>
					<li>NO JUGAR CON LOS ARTICULOS PARA TRABAJO DE MORDIDA (PARA EVITAR ACCIDENTES)</li>
					<li>LLEGAR A LA HORA CONVENIDA AL CLUB 10 MIN DE TOLERANCIA NO MAS</li>
					<li>A PARTIR DE LAS 8 AM CON TOLERANCIA 8:10AM</li>
					<li>QUE EL PERRO VAYA EN BUEN ESTADO DE SALUD</li>
					<li>CONFORME VAYAN LLEGANDO SE LES IRA ATENDIENDO</li>
					<li>LAS HEMBRAS NO DEBEN DE ESTAR EN CELO</li>
				</ol>
				<h2>EJERCICIOS PARA EL CLUB</h2>
				<h2>GRUPO I</h2>
				<h2>BASICOS Y AVANZADOS</h2>
				<p>PARTE DE ESTOS EJERCICIOS DE ADIESTRAMIENTO CANINO, QUE RESPONDEN A LAS ORDENES DE, "JUNTO", "SENTADO", "ABAJO", "QUIETO" Y "AQUI", PUEDEN SER UTILIZADOS COTIDIANAMENTE CON DIVERSOS FINES PRACTICOS, TANTOS, COMO A SUS DUE&NtildeOS SE LES OCURRAN.</p>
				<p>ADEMAS, DURANTE EL PROCESO, NUESTROS PERROS TAMBIEN DEBERA APRENDER LOS REFUERZOS "NO" Y "MUY BIEN" COMO NEGATIVO Y POSITIVO RESPECTIVAMENTE.</p>
				<h2>"JUNTO"</h2>
				<p>CON ESTE EJERCICIO, SE LE ENSE&NtildeA AL PERRO A QUE, CUANDO ESTA BAJO ESTA ORDEN, DEBE CAMINAR A NUESTRO LADO SIN TIRAR DE LA CORREA, Y AL RITMO QUE LO HAGA SU GUIA. ADEMAS, TAMBIEN APRENDERA DURANTE ESTE EJERCICIO, A NO LADRAR A OTROS ANIMALES, O PERSONAS DURANTE LOS PASEOS, Y A NO ABALANZARSE A POR CICLISTAS, CORREDORES, COCHES ETC....</p>
				<h2>"SENTADO"</h2>
				<p>CON ESTE EJERCICIO CANINO, SE LE ENSE&NtildeA A QUE SE SIENTE AL DARLE LA ORDEN "SIENTA", ADEMAS, APRENDERA QUE CUANDO ESTA BAJO LA ORDEN "JUNTO" Y SU GUIA SE DETIENE, EL DEBE SENTARSE AUN EN AUSENCIA DE LA ORDEN "SIENTA". EJEMPLOS DE APLICACIONES PRACTICAS SERIAN: AL PARARNOS A SALUDAR A ALGUIEN, EL PERRO DEBERA SENTARSE, DE ESTE MODO NO SE TIRARA ENCIMA DE ESA PERSONA PARA SALUDARLA Y LO PODRAN ACARICIAR SIN TENER QUE ESTAR ESQUIVANDO SUS PATAS. AL ABRIR LA PUERTA DE CASA, EL PERRO HA DE PERMANECER SENTADO A NUESTRO LADO, SIN DAR TIRONES PARA SER EL PRIMERO EN ENTRAR. AL METERLO EN EL COCHE, TAMBIEN LO SENTAREMOS ANTES DE ABRIR LA PUERTA Y UNA VEZ ABIERTA LE DAREMOS LA ORDEN PARA QUE PASE. EN PASOS DE PEATONES Y SEMAFOROS DEBERA SENTARSE EL SOLO NADA MAS LLEGAR. PARA PONERLE LA CORREA O EL COLLAR, EN VEZ DE ANDAR "PELEANDO" CON EL, LE DAMOS LA ORDEN SIENTA Y SE LO PONEMOS TRANQUILAMENTE. ETC..</p>
				<h2>"ABAJO"</h2>
				<p>CON ESTE EJERCICIO CANINO DE ENTRENAMIENTO, APRENDERA A TUMBARSE CUANDO EL GUIA SE LO ORDENE, Y DURANTE EL TIEMPO QUE SEA NECESARIO, EN PRESENCIA DEL GUIA.</p>
				<h2>"QUIETO"</h2>
				<p>ESTA ORDEN, LA RESERVAREMOS PARA SITUACIONES ESPECIALES, EN LAS QUE, TRAS HABERLO SENTADO O TUMBADO, NOS QUERAMOS ALEJAR MAS DE LO HABITUAL, O A DESAPARECER DE SU VISTA DURANTE UN PERIODO DE TIEMPO CORTO. TENDRA UN EFECTO REFORZADOR SOBRE LA ORDEN QUE ESTE REALIZANDO, DANDOLE A ENTENDER AL PERRO, QUE DEBERA MANTENER LA POSICION, Y NO PREOCUPARSE, PORQUE VOLVERAS A POR EL.</p>
				<p>ESTAS ORDENES, SON APLICABLES A CUALQUIER SITUACION EN LA QUE NOS ENCONTREMOS, EN QUE NECESITEMOS QUE NUESTRO PERRO SE ESTE QUIETO DURANTE UN MOMENTO, O DURANTE UN PERIODO ALGO MAS LARGO DE TIEMPO.</p>
				<p>EJEMPLOS DE ELLO: VISITAS EN CASA, NECESIDAD DE DEJAR UNA PUERTA ABIERTA SIN QUE EL PASE DENTRO O SE ESCAPE, PARA TOMAR ALGO EN UNA TERRAZA, ENTRAR A COMPRAR ALGO EN UNA TIENDA EN LA PLAYA O EL CAMPO CUANDO PREVEEMOS QUE PUEDA INCORDIAR A ALGUIEN...ETC.</p>
				<h2>"AQUI"</h2>
				<p>EL PERRO, HA DE ACUDIR A LA LLAMADA DE SU DUE&NtildeO, SIEMPRE.</p>
				<p>ESTE EJERCICIO CANINO BASICO, ES MUY IMPORTANTE, EN LA EDUCACION DE UN PERRO, PORQUE SI NO ACUDE RAPIDAMENTE, UN DIA U OTRO, PODEMOS TENER UN PROBLEMA SERIO, PUESTO QUE EL PERRO, PUEDE TIRAR A ALGUIEN, PUEDE CREAR UN ACCCIDENTE DE TRAFICO, ETC...</p>
				<h2><span>NOTA</span></h2>
				<p>ESTOS EJERCICIOS SERAN REALIZADOS TAMBIEN SIN CORREA A CONSIDERACION DEL INSTRUCTOR EJERCICIOS PARA EL CLUB</p>
				<h2>GRUPO II</h2>
				<h2>GUARDIAS BASICAS</h2>
				<p> DEFENSA DE MANEJADOR <br>
					ATAQUE DE FRENTE CON VAREO <br>
					EL FALSO ATAQUE DE FRENTE CON VAREO <br>
					ATAQUE EN HUIDA CON VAREO
				</p>

<?php 

	 require '../visual/include/aside.php';

?>

<?php 

	 require '../visual/include/footer.php';

?>